//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : DigitalIO.cpp
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#include "DigitalIO.h"

uint8_t DigitalIO::getPIN() {
	return this->pin->getPIN();
}

boolean DigitalIO::getPullUp() {
	return this->pullup;
}