//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LED.cpp
//  @ Date : 20.10.2014
//  @ Author :
//
//


#include "../../interfaces/output/LED.h"

void LED::turnOn() {
	this->write(true);
}

void LED::turnOff() {
	this->write(false);
}

void LED::toggle() {
	//call super
	((DigitalIOGeneric*) this)->toggle();
}

boolean LED::implementsInterface( HardwareTypeIdentifier type ) {
	if(type == HWTYPE_led)
		return true;
	return false;
}

boolean LED::readVal( HardwareTypeIdentifier type, HardwareCommandResult* result ) {
	if(type == HWTYPE_led && result != NULL)
		return DigitalIOGeneric::readVal(HWType_DIGITAL, result);
	return false;
}

boolean LED::writeVal( HardwareTypeIdentifier type, HardwareCommandResult* result ) {
	if(type == HWTYPE_led && result != NULL)
		return DigitalIOGeneric::writeVal(HWType_DIGITAL, result);

	return false;
}

boolean LED::read() {
	return false;
}