//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LED.h
//  @ Date : 20.10.2014
//  @ Author :
//
//


#if !defined(_LED_H)
#define _LED_H

#include <Arduino.h>
#include <drivers/HardwareID.h>
#include <drivers/DigitalIOGeneric.h>

class LED : public DigitalIOGeneric {
	public:
		/**
		 * @param pin
		 * @param address
		 */
		void init(uint8_t pin, uint8_t hwaddress) {
			DigitalIOGeneric::init(pin, hwaddress);
		}
		void turnOn();
		void turnOff();
		void toggle();

		boolean implementsInterface( HardwareTypeIdentifier type );

		HardwareTypeIdentifier* getImplementedInterfaces(HardwareTypeIdentifier* arr, uint8_t maxLen);

		/**
		 * @param type
		 * @param result:
		 *        - uintliust[0]: 0=off, 1=on
		 */
		boolean readVal( HardwareTypeIdentifier type, HardwareCommandResult* result );

		/**
		 * @param type
		 * @result result
		 *         - uintlist[0]: 0=off, 1=on, 2=toggle
		 */
		boolean writeVal( HardwareTypeIdentifier type, HardwareCommandResult* result );

		/**
		 * @return false
		 */
		boolean read();
};

#endif  //_LED_H
