//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Relay.h
//  @ Date : 20.10.2014
//  @ Author :
//
//


#if !defined(_RELAY_H)
#define _RELAY_H

#include <Arduino.h>
#include <drivers/HardwareID.h>
#include <drivers/DigitalIOGeneric.h>

class Relay : public DigitalIOGeneric {
	public:
		void init(uint8_t pin, uint8_t hwaddress) {
			DigitalIOGeneric::init(pin, false, hwaddress);
		}

		void init(uint8_t pin, boolean highIsOn, uint8_t hwaddress) {
			DigitalIOGeneric::init(pin, false, hwaddress);
			this->highIsOn = highIsOn;
		}

		boolean highIsOn;
		void turnOn();
		void turnOff();
		virtual boolean outputRead() = 0;
		virtual void outputRead(HardwareCommandResult* hwresult) = 0;

		boolean implementsInterface( HardwareTypeIdentifier type );

		/**
		 * @param type
		 * @param result:
		 *        - uintliust[0]: 0=off, 1=on
		 */
		boolean readVal( HardwareTypeIdentifier type, HardwareCommandResult* result );

		/**
		 * @param type
		 * @result result
		 *         - uintlist[0]: 0=off, 1=on, 2=toggle
		 */
		boolean writeVal( HardwareTypeIdentifier type, HardwareCommandResult* result );


		HardwareTypeIdentifier* getImplementedInterfaces(HardwareTypeIdentifier* arr, uint8_t maxLen) {
			DigitalIOGeneric::getImplementedInterfaces(arr, maxLen);
			return this->addImplementedInterface(arr, maxLen, HWType_relay);
		}

	private:
		boolean read();
		void write( int boolean );
		void toggle();


};

#endif  //_RELAY_H
