//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Multiplexible.h
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#if !defined(_MULTIPLEXIBLE_H)
#define _MULTIPLEXIBLE_H

#include <Arduino.h>

class Multiplexible {
public:
	virtual uint8_t getPIN() = 0;
};

#endif  //_MULTIPLEXIBLE_H
