//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Multiplexed.h
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#if !defined(_MULTIPLEXED_H)
#define _MULTIPLEXED_H

#include <Arduino.h>
#include "Multiplexible.h"

class Multiplexed : public Multiplexible {
public:
	int* AddressLanes;
	int* DataLanes;
	int usedPIN;

	uint8_t numDataLanes;
	uint8_t numAddressLanes;

	uint8_t getPIN();
};

#endif  //_MULTIPLEXED_H
