//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : NoMultiplex.h
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#if !defined(_NOMULTIPLEX_H)
#define _NOMULTIPLEX_H

#include <Arduino.h>
#include "Multiplexible.h"

class NoMultiplex : public Multiplexible {
public:
	NoMultiplex(uint8_t pin) {
		this->PIN = pin;
	};
	
	uint8_t PIN;
	uint8_t getPIN() {
		return PIN;
	}
};

#endif  //_NOMULTIPLEX_H
