//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : InputDevice.h
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#if !defined(_INPUTDEVICE_H)
#define _INPUTDEVICE_H

#include <Arduino.h>
#include "../../HardwareDriver.h"

class InputDevice : public HardwareDriver {
};

#endif  //_INPUTDEVICE_H
