//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : KeyPad4x4.h
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#if !defined(_KEYPAD4X4_H)
#define _KEYPAD4X4_H

#include <Arduino.h>
#include "../../interfaces/KeyPad.h"

namespace inoutput {
	class KeyPad4x4 : public KeyPad {
	};
}

#endif  //_KEYPAD4X4_H
