//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LCD.h
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#if !defined(_LCD_H)
#define _LCD_H

#include <Arduino.h>
#include "OutputDevice.h"

namespace inoutput {
	class LCD : public OutputDevice {
	};
}

#endif  //_LCD_H
