//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : OutputDevice.cpp
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#include "OutputDevice.h"

namespace inoutput {
	void OutputDevice::print(String content) {
	
	}
	
}
