//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : OutputDevice.h
//  @ Date : 20.10.2014
//  @ Author :
//
//


#if !defined(_OUTPUTDEVICE_H)
#define _OUTPUTDEVICE_H

#include <Arduino.h>
#include <drivers/HardwareDriver.h>

namespace inoutput {
	class OutputDevice : public HardwareDriver {
	public:
		void print(String content);
	};
}

#endif  //_OUTPUTDEVICE_H
