//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Serial.h
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#if !defined(_SERIAL_H)
#define _SERIAL_H

#include <Arduino.h>
#include "OutputDevice.h"
#include "InputDevice.h"

namespace inoutput {
	class Serial : public OutputDevice, public InputDevice {
	};
}

#endif  //_SERIAL_H
