//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Switch.cpp
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#include "../../interfaces/input/Switch.h"

boolean Switch::read() {
	return false;	
}