//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TFT.h
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#if !defined(_TFT_H)
#define _TFT_H

#include <Arduino.h>
#include "OutputDevice.h"

namespace inoutput {
	class TFT : public OutputDevice {
	};
}

#endif  //_TFT_H
