//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Tochpad.cpp
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#include "../../interfaces/input/Tochpad.h"

Tuple<uint16_t> Tochpad::read() {
	Tuple<uint16_t> tuple = Tuple<uint16_t>(1, 2);
	return tuple;
}
