//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Accelerometer.h
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#if !defined(_ACCELEROMETER_H)
#define _ACCELEROMETER_H

#include "../../utils/Triple.h"
#include "../../HardwareID.h"
#include <dispatcher/Commands.h>

class Accelerometer {
	public:
		virtual Triple<int16_t> readAccels()=0;
		virtual void readAccels(HardwareCommandResult* hwresult)=0;
};

#endif  //_ACCELEROMETER_H
