//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Button.h
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#if !defined(_BUTTON_H)
#define _BUTTON_H

#include <Arduino.h>
#include "../../HardwareID.h"
#include "../../drivers/inoutput/InputDevice.h"
#include <dispatcher/Commands.h>

class Button : public InputDevice {
	public:
		Button();
		virtual boolean read()=0;
		virtual void read(HardwareCommandResult* hwresult)=0;
};

#endif  //_BUTTON_H
