//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : KeyPad.h
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#if !defined(_KEYPAD_H)
#define _KEYPAD_H

#include <Arduino.h>
#include "../../drivers/inoutput/InputDevice.h"
#include "../../HardwareID.h"
#include <dispatcher/Commands.h>

class KeyPad : public InputDevice {
	public:
		KeyPad();
		virtual char read();
		virtual void read(HardwareCommandResult* hwresult)=0;
};

#endif  //_KEYPAD_H
