/*
 * Light.h
 *
 * Created: 14.05.2015 15:17:40
 *  Author: helge
 */


#ifndef LIGHT_H_
#define LIGHT_H_


//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Methane.h
//  @ Date : 20.10.2014
//  @ Author :
//
//


#include <Arduino.h>
#include <drivers/AnalogIOGeneric.h>

class Light : public AnalogIOGeneric {
	public:
	Light(Multiplexible* pin) : AnalogIOGeneric(pin) {
	}
	Light(uint8_t pin) : AnalogIOGeneric(pin) {
	}

	virtual boolean implementsInterface( HardwareTypeIdentifier type );

	virtual boolean readVal( HardwareTypeIdentifier type, HardwareCommandResult* result );

	private:
	virtual boolean writeVal( HardwareTypeIdentifier type, HardwareCommandResult* result ) {
		return false;
	}

	virtual HardwareTypeIdentifier* getImplementedInterfaces(HardwareTypeIdentifier* arr, uint8_t maxLen) {
		AnalogIOGeneric::getImplementedInterfaces(arr, maxLen);
		return this->addImplementedInterface(arr, maxLen, HWType_light);
	}

};

#endif /* LIGHT_H_ */