//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MagneticField.h
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#if !defined(_MAGNETICFIELD_H)
#define _MAGNETICFIELD_H

#include <Arduino.h>
#include "../../utils/Triple.h"
#include "../../HardwareID.h"
#include <dispatcher/Commands.h>

class MagneticField {
	public:
		MagneticField();
		virtual Triple<int16_t> readMagnetic()=0;
		virtual void readMagnetic(HardwareCommandResult* hwresult)=0;
};

#endif  //_MAGNETICFIELD_H
