//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Methane.h
//  @ Date : 20.10.2014
//  @ Author :
//
//


#if !defined(_METHANE_H)
#define _METHANE_H

#include <Arduino.h>
#include <drivers/AnalogIOGeneric.h>

class Methane : public AnalogIOGeneric {
	public:
		Methane(Multiplexible* pin) : AnalogIOGeneric(pin) {
		}
		Methane(uint8_t pin) : AnalogIOGeneric(pin) {
		}

		virtual boolean implementsInterface( HardwareTypeIdentifier type );

		virtual boolean readVal( HardwareTypeIdentifier type, HardwareCommandResult* result );

	private:
		virtual boolean writeVal( HardwareTypeIdentifier type, HardwareCommandResult* result ) {
			return false;
		}

		virtual HardwareTypeIdentifier* getImplementedInterfaces(HardwareTypeIdentifier* arr, uint8_t maxLen) {
			AnalogIOGeneric::getImplementedInterfaces(arr, maxLen);
			return this->addImplementedInterface(arr, maxLen, HWType_methane);
		}

};

#endif  //_METHANE_H
