//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Methane.h
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#if !defined(_METHANE_H)
#define _METHANE_H

#include <Arduino.h>
#include "../../interfaces/AnalogIOGeneric.h"

class Methane : public AnalogIOGeneric {
	public:
		Methane(Multiplexible* pin) : AnalogIOGeneric(pin) {
		}
		Methane(uint8_t pin) : AnalogIOGeneric(pin) {
		}

		virtual boolean implementsInterface( HardwareTypeIdentifier type );

		virtual boolean readVal( HardwareTypeIdentifier type, HardwareCommandResult* result );

	private:
		virtual boolean writeVal( HardwareTypeIdentifier type, HardwareCommandResult* result ) {
			return false;
		}

};

#endif  //_METHANE_H
