//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pressure.h
//  @ Date : 20.10.2014
//  @ Author :
//
//


#if !defined(_PRESSURE_H)
#define _PRESSURE_H

#include <Arduino.h>
#include <drivers/HardwareID.h>
#include <drivers/HardwareDriver.h>
#include <dispatcher/Commands.h>

class Pressure {
	public:
		virtual uint16_t readPressure()=0;
		virtual void readPressure(HardwareCommandResult* hwresult)=0;
		virtual uint16_t getAltitude()=0;
		virtual void getAltitude(HardwareCommandResult* hwresult)=0;
};

#endif  //_PRESSURE_H
