//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : RFID.h
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#if !defined(_RFID_H)
#define _RFID_H

#include <Arduino.h>
#include "../../drivers/spi/SPI.h"

class RFID : public SPIbase {
};

#endif  //_RFID_H
