//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SDCard.h
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#if !defined(_SDCARD_H)
#define _SDCARD_H

#include <Arduino.h>
#include "../../drivers/spi/SPI.h"

namespace spi {
	class SDCard : public SPIbase {
	public:
		void getSdCardObject();
	};
}

#endif  //_SDCARD_H
