//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Sonar.h
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#if !defined(_SONAR_H)
#define _SONAR_H

#include <Arduino.h>
#include "../../drivers/i2c/I2C.h"
#include "../../HardwareID.h"
#include <dispatcher/Commands.h>


class Sonar : public I2C {
	public:
		virtual uint8_t read() = 0;
		//void setMaxDistance(float cm);
		virtual  void read(HardwareCommandResult* hwresult) = 0;
		
		Sonar() {
			this->address = 0x43;
			Wire.begin();
		}

		virtual boolean readVal( HardwareTypeIdentifier type, HardwareCommandResult* result );

		virtual boolean implementsInterface( HardwareTypeIdentifier type );

};

#endif  //_SONAR_H
