//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Switch.h
//  @ Date : 20.10.2014
//  @ Author :
//
//


#if !defined(_SWITCH_H)
#define _SWITCH_H

#include <Arduino.h>
#include <drivers/inoutput/InputDevice.h>
#include <drivers/HardwareID.h>
#include <dispatcher/Commands.h>

class Switch {
	public:
		virtual boolean read();
		virtual void read(HardwareCommandResult* hwresult) = 0;
};

#endif  //_SWITCH_H
