//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Temperature.h
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#if !defined(_TEMPERATURE_H)
#define _TEMPERATURE_H

#include <Arduino.h>
#include "../../HardwareID.h"
#include "../../HardwareDriver.h"
#include <dispatcher/Commands.h>

class Temperature {
	public:
		virtual int readTemperature()=0;
		virtual void readTemperature(HardwareCommandResult* hwresult)=0;
};

#endif  //_TEMPERATURE_H
