//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Tochpad.h
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#if !defined(_TOCHPAD_H)
#define _TOCHPAD_H

#include <Arduino.h>
#include "../../drivers/inoutput/InputDevice.h"
#include "../../utils/tuple.h"

class Tochpad : public InputDevice {
	public:
		//Touchpad() : HardwareInterface(HWType_touchpad) {};
		virtual Tuple<uint16_t> read() = 0;
};

#endif  //_TOCHPAD_H
