/*
 * LayerConfig.h
 *
 * Created: 07.01.2015 21:41:42
 *  Author: helge
 */


#ifndef LAYERCONFIG_H_
#define LAYERCONFIG_H_
#include "../DebugConfig.h"

	#define CONFIG_L2_RECEIVE_BUFFER_LEN 3

	#define CONFIG_RF_PA_LEVEL RF24_PA_LOW
	#define CONFIG_RF_CHANNEL 70
	#define CONFIG_CRC RF24_CRC_16 //RF24_CRC_DISABLED //RF24_CRC_8
	#define CONFIG_RF_DATARATE RF24_250KBPS //RF24_1MBPS //RF24_250KBPS //RF24_2MBPS
	#define CONFIG_L2_PAYLOAD_SIZE 32
	#define CONFIG_L2_RETRY_MAX 15
	#define CONFIG_L2_RETRY_DELAY_250US 15

	#define CONFIG_L2_ADDR_BROADCAST	0x000000FFFFLL
	#define CONFIG_RF_PIPE_BROADCAST	0 //pipe 0 and 1..5 must be used
	#define CONFIG_RF_PIPE_DEVICE		1
	//#define CONFIG_DEVICE_ADDRESS_LOW 0x0000000000LL
	//#define CONFIG_DEVICE_ADDRESS_HIGH 0xFFFFFFFFF0LL

	#define CONFIG_L3_ADDRESS_BROADCAST CONFIG_L2_ADDR_BROADCAST

	#define CONFIG_L3_PAYLOAD_SIZE (CONFIG_L2_PAYLOAD_SIZE - 5) //5b l2 overhead
	#define CONFIG_APP_PAYLOAD_SIZE (CONFIG_L3_PAYLOAD_SIZE - 7) //7b l3 overhead

	#define CONFIG_L3_BEACON_PERIOD_MS (30*1000L)
	#define CONFIG_L3_NEIGHBOUR_MAX_AGE_MS (300*1000L)

	#define CONFIG_L3_MAX_HOPCOUNT 10

	typedef uint16_t l3_seq_t;
	typedef uint32_t l3_timestamp;
	typedef uint16_t l3_address_t;
	#define CONFIG_L3_NUM_NEIGHBOURS 15

	#define CONFIG_L3_RECEIVE_BUFFER_LEN 5
	#define CONFIG_L3_SEND_BUFFER_LEN 5
	#define CONFIG_L3_NUMBERED_RETRANSMISSIONS 3
	#define CONFIG_L3_NUMBERED_TIMEOUT_MS (1000)

	enum l3_packetType {PACKET_ACK, PACKET_NUMBERED, PACKET_UNNUMBERED, PACKET_BEACON};

#endif /* LAYERCONFIG_H_ */