//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MFRC522.cpp
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#include "MFRC522.h"

void MFRC522::getRFIDObject() {
	
}
