//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MFRC522.h
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#if !defined(_MFRC522_H)
#define _MFRC522_H

#include <Arduino.h>
#include "../../interfaces/input/RFID.h"

class MFRC522 : public RFID {
	public:
		void getRFIDObject();
};

#endif  //_MFRC522_H
