//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SDCard.cpp
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#include "../../interfaces/input/SDCard.h"

namespace spi {
	void SDCard::getSdCardObject() {
	
	}
	
}
