//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SPI.h
//  @ Date : 20.10.2014
//  @ Author :
//
//


#if !defined(_SPI_H)
#define _SPI_H

#include <Arduino.h>
#include <drivers/HardwareDriver.h>

class SPIbase : public HardwareDriver {
	public:
		int ChipSelectPIN;
};

#endif  //_SPI_H
