//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : I2C.h
//  @ Date : 20.10.2014
//  @ Author :
//
//


#if !defined(_I2C_H)
#define _I2C_H

#include <Arduino.h>
#include <drivers/HardwareDriver.h>
#include <Wire.h>

class I2C : public HardwareDriver {
	public:
		uint8_t address;

		virtual HardwareTypeIdentifier* getImplementedInterfaces(HardwareTypeIdentifier* arr, uint8_t maxLen) = 0;
};

#endif  //_I2C_H
