//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ethernet.cpp
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#include "Ethernet.h"

namespace ethernet {
	void Ethernet::sendData(IPAddress dest, byte* content, uint32_t len) {
	
	}
	
}
