//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ethernet.h
//  @ Date : 20.10.2014
//  @ Author :
//
//


#if !defined(_ETHERNET_H)
#define _ETHERNET_H

#include <Arduino.h>
#include <drivers/HardwareDriver.h>
#include <IPAddress.h>

namespace ethernet {
	class Ethernet : public HardwareDriver {
	public:
		IPAddress localAddress;
		void sendData(IPAddress dest, byte* content, uint32_t len);
	};
}

#endif  //_ETHERNET_H
