//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : AnalogIO.cpp
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#include "AnalogIO.h"

uint8_t AnalogIO::getPIN() {
	return this->pin->getPIN();
}	
