//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : AnalogIOGeneric.h
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#if !defined(_ANALOGIOGENERIC_H)
#define _ANALOGIOGENERIC_H

#include <Arduino.h>
#include "../drivers/analogio/AnalogIO.h"

class AnalogIOGeneric : public AnalogIO {
	public:
		uint8_t read();
		void write(uint8_t val);
};

#endif  //_ANALOGIOGENERIC_H
