//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : DigitalIOGeneric.h
//  @ Date : 20.10.2014
//  @ Author : 
//
//


#if !defined(_DIGITALIOGENERIC_H)
#define _DIGITALIOGENERIC_H

#include <Arduino.h>
#include "../drivers/digitalio/DigitalIO.h"

class DigitalIOGeneric : public DigitalIO {
public:
	DigitalIOGeneric(uint8_t pin) : DigitalIO(pin) {
	}
	DigitalIOGeneric(uint8_t pin, boolean pullup) : DigitalIO(pin, pullup) {
	}
	boolean read();
	virtual boolean outputRead();
	void write(int boolean);
	void toggle();
};

#endif  //_DIGITALIOGENERIC_H
